Repository Arquisoft/dede_es1b, pull requests merged in 2022-04, with the labels that each got.

#130 Documentación actualizada
  docs/02_architecture_constraints.adoc
  docs/09_design_decisions.adoc
Labels: documentation

#133 Front ayuda
  webapp/src/App.tsx
  webapp/src/pages/ayudaPage/ayuda.tsx
  webapp/src/pages/ayudaPage/ayudaPage.css
  webapp/src/pages/menuBar.tsx
Labels: desarrollo

#134 Control de inicio de sesión a través de token
  restapi/usuarios/ControladorUsuario.ts
  restapi/usuarios/GenerarToken.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/pages/bienvenidaPage/bienvenidaPage.tsx
  webapp/src/pages/catalogoPage/catalogo.tsx
  webapp/src/pages/logginPage/LogginForm.tsx
  webapp/src/pages/menuBar.tsx
  webapp/src/pages/menuBarAdmin.tsx
  webapp/src/pages/registroPage/registro.tsx
Labels: desarrollo

#142 Funcionalidad del carrito
  webapp/src/App.tsx
  webapp/src/components/Productos.css
  webapp/src/components/Productos.tsx
  webapp/src/components/carrito/Carrito.tsx
  webapp/src/components/carrito/ProductoCarrito.tsx
  webapp/src/components/carrito/carrito.css
  webapp/src/pages/mainPage/CardProducto.tsx
  webapp/src/pages/mainPage/Homepage.tsx
  webapp/src/pages/mainPage/ListaProductos.tsx
  webapp/src/pages/mainPage/homepage.css
  webapp/src/pages/mainPage/listaProductos.css
  webapp/src/pages/menuBar.tsx
  webapp/src/pages/productosPorCategoria/productosPorCategoria.css
  webapp/src/pages/productosPorCategoria/productosPorCategoria.tsx
  webapp/src/shared/shareddtypes.ts
Labels: desarrollo, frontend

#151 Ventana detalles de producto añadida
  webapp/server.ts
  webapp/src/App.tsx
  webapp/src/pages/ayudaPage/ayuda.tsx
  webapp/src/pages/ayudaPage/ayudaPage.css
  webapp/src/pages/mainPage/CardProducto.tsx
  webapp/src/pages/mainPage/Homepage.tsx
  webapp/src/pages/menuBar.tsx
  webapp/src/pages/productPage/productPage.css
  webapp/src/pages/productPage/productPage.tsx
  webapp/src/pages/productPage/productPageDesarrollo.tsx
Labels: desarrollo

#167 Ventana de compra
  webapp/src/App.tsx
  webapp/src/components/carrito/Carrito.tsx
  webapp/src/components/carrito/carrito.css
  webapp/src/components/pago/ProductoPedido.tsx
  webapp/src/components/pago/pago.css
  webapp/src/pages/mainPage/CardProducto.tsx
  webapp/src/pages/mainPage/Homepage.tsx
  webapp/src/pages/mainPage/homepage.css
  webapp/src/pages/pagoPage/PagoFinalizado.tsx
  webapp/src/pages/pagoPage/VentanaPago.tsx
Labels: desarrollo, frontend

#168 Sergio test
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
Labels: backend

#187 Cálculo gastos de envío a partir de dirección
  webapp/src/api/api.ts
  webapp/src/components/pago/pago.css
  webapp/src/pages/pagoPage/VentanaPago.tsx
Labels: desarrollo, frontend

#188 Arreglada inconsistencia del carrito
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/carrito/Carrito.tsx
  webapp/src/pages/mainPage/Homepage.tsx
  webapp/src/pages/pagoPage/VentanaPago.tsx
  webapp/src/pages/productosPorCategoria/productosPorCategoria.tsx
Labels: desarrollo, frontend

#192 Actualizado código para utilizar imágenes del repositorio
  webapp/src/components/carrito/ProductoCarrito.tsx
  webapp/src/components/pago/ProductoPedido.tsx
  webapp/src/pages/bienvenidaPage/bienvenidaPage.css
  webapp/src/pages/catalogoPage/catalogo.tsx
  webapp/src/pages/mainPage/CardProducto.tsx
  webapp/src/pages/menuBar.tsx
  webapp/src/pages/productPage/productPage.tsx
  webapp/src/pages/productPage/productPageDesarrollo.tsx
Labels: frontend, diseño
