Repository Arquisoft/dede_es1b, pull requests merged in 2022-03, with the labels that each got.

#63 Apartado 9 doc
  docs/09_design_decisions.adoc
Labels: documentation

#76 Página de inicio
  webapp/src/App.tsx
  webapp/src/api/modelo/producto.ts
  webapp/src/components/CardProducto.tsx
  webapp/src/components/ListaProductos.css
  webapp/src/components/ListaProductos.tsx
  webapp/src/images/prod1.jpg
  webapp/src/images/prod2.jpg
  webapp/src/images/prod3.jpg
  webapp/src/pages/Homepage.tsx
  webapp/src/pages/homepage.css
Labels: desarrollo, frontend

#85 Arreglada vista de productos
  webapp/src/images/callos.png
  webapp/src/images/compango.png
  webapp/src/images/fabada.png
  webapp/src/images/horreos.png
  webapp/src/images/prod1.jpg
  webapp/src/images/prod2.jpg
  webapp/src/images/prod3.jpg
  webapp/src/images/sidra.png
  webapp/src/pages/mainPage/CardProducto.tsx
  webapp/src/pages/mainPage/Homepage.tsx
  webapp/src/pages/mainPage/ListaProductos.css
  webapp/src/pages/mainPage/ListaProductos.tsx
  webapp/src/pages/mainPage/homepage.css
Labels: desarrollo, frontend

#117 Productos backend-frontend
  restapi/package-lock.json
  restapi/package.json
  webapp/src/api/api.ts
  webapp/src/components/Productos.css
  webapp/src/components/Productos.tsx
  webapp/src/images/cajasidra.png
  webapp/src/images/horreo.png
  webapp/src/images/latacallos.png
  webapp/src/pages/mainPage/CardProducto.tsx
  webapp/src/pages/mainPage/ListaProductos.tsx
Labels: desarrollo, backend, frontend

#123 Añadida ventana Catálogo
  webapp/src/App.tsx
  webapp/src/images/camiseta.png
  webapp/src/images/categoriaAdornos.png
  webapp/src/images/categoriaRopa.png
  webapp/src/images/cortina.png
  webapp/src/images/fabadaIcono.png
  webapp/src/images/horreo.png
  webapp/src/pages/bienvenidaPage/bienvenidaPage.css
  webapp/src/pages/bienvenidaPage/bienvenidaPage.tsx
  webapp/src/pages/catalogoPage/catalogo.css
  webapp/src/pages/catalogoPage/catalogo.tsx
  webapp/src/pages/logginPage/LogginForm.tsx
  webapp/src/pages/logginPage/logginForm.css
  webapp/src/pages/mainPage/Homepage.tsx
  webapp/src/pages/mainPage/ListaProductos.tsx
  webapp/src/pages/mainPage/homepage.css
  webapp/src/pages/mainPage/listaProductos.css
  webapp/src/pages/menuBar.css
  webapp/src/pages/menuBar.tsx
  webapp/src/pages/registroPage/registro.css
  webapp/src/pages/registroPage/registro.tsx
Labels: desarrollo

#124 base tokens acabada
  restapi/package-lock.json
  restapi/package.json
  restapi/usuarios/ControladorUsuario.ts
  restapi/usuarios/GenerarToken.ts
  webapp/package-lock.json
Labels: backend

#125 Funcionalidad carrito y busqueda por categorias
  package-lock.json
  package.json
  restapi/carritos/ControladorCarrito.ts
  restapi/carritos/ModelCarrito.ts
  restapi/carritos/routerCarrito.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/productos/controladorProducto.ts
  restapi/productos/routerProductos.ts
  restapi/usuarios/ControladorUsuario.ts
  restapi/usuarios/modeloUsuario.ts
  webapp/src/api/api.ts
Labels: backend
